services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - IS_DEV_DOCKER=true
    extra_hosts:
      - "local:host-gateway"  
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      # export port for debugging
      # different port in case default one on local machine already used
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=saskatoon_dev
      - MYSQL_USER=saskatoon
      - MYSQL_PASSWORD=saskatoon
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
